Random forest 1
Rakesh9100/ML-Project-Drug-Review-Dataset pull request #87
Opened 2023-06-02 08:19 UTC by sreyaad

# Fixes Issue🛠️

Closes #70 

# Description👨‍💻 

- Random Forest Classifier with Random Under Sampler
# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have added demonstration in the form of GIF/video file
- [✅] I am an Open Source Contributor

# Screenshots/GIF📷
![image](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/assets/74537679/d28e6ac1-300a-4a7a-9da3-02468998a351)

2023-06-02 08:27 UTC, Neilblaze commented on main.py
> +pred = clf2.predict(X_test)
I'll recommend using `pred1` here and updating the changes accordingly.

2023-06-02 08:28 UTC, Neilblaze commented on main.py
> +pred = clf3.predict(X_test)
Similarly, use `pred2` here & update the changes accordingly.

2023-06-02 08:28 UTC, Neilblaze requested changes
Make the changes, and rest LGTM!

2023-06-02 18:34 UTC, Rakesh9100 commented
@sreyaad Pls make the requested changes

2023-06-07 17:52 UTC, Rakesh9100 commented
Closing for no response.

2023-06-07 17:52 UTC, closed without merging